/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk1_Simple */

#ifndef _Included_ndk1_Simple
#define _Included_ndk1_Simple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk1_Simple
 * Method:    getStirngnaturePassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndk1_Simple_getStirngnaturePassword
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
