/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk1_Simple2 */

#ifndef _Included_ndk1_Simple2
#define _Included_ndk1_Simple2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk1_Simple2
 * Method:    changeName
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ndk1_Simple2_changeName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
